### ISSUE TITLE
Add ‎S0722540 SKU

### ISSUE THREAD

**Issue by twisted-space** [free-dmo/free-dmo-stm32#18]
Dumped by FreeDMO TagDump

inventory: 0x01,0x77,0x16,0x15,0x29,0x08,0x01,0x04,0xE0
sysInfo: 0x0F,0x77,0x16,0x15,0x29,0x08,0x01,0x04,0xE0,0x01,0x3D,0x4F,0x03,0x01
signature: 0xE7,0x63,0x11,0x38,0xCF,0x8E,0xE3,0x14,0xE6,0x90,0xD2,0x3E,0x80,0xA9,0x0B,0x5B,0x7C,0x3C,0x73,0xAF,0x6B,0x5D,0x2F,0x18,0x79,0xD9,0x14,0x99,0xA7,0x88,0x50,0x10
blocks:
0x03,0x0A,0x82,0xED,0x86,0x39,0x61,0xD2,0x03,0x14,0x1E,0x32,0xB6,0xCA,0x00,0x3C,0x82,0xEB,0xEE,0x6F,0x53,0x30,0x37,0x32,0x32,0x35,0x34,0x30,0x00,0x00,0x00,0x00,0x00,0xFF,0x06,0x01,0x01,0x00,0x00,0x00,0x9D,0x01,0x1E,0x00,0x58,0x00,0x00,0x00,0x00,0x00,0x19,0x00,0x3D,0x01,0x3B,0x02,0x00,0x00,0x00,0x00,0x6B,0x02,0xE8,0x03, 0xA0,0x50,0x64,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xD7,0xFA,0x00,0x1C,0xEC,0xE7,0x36,0x9F,0x00,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x30,0x00,0x00,0x00,0xE8,0x49,0x6B,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x32,0x8C,0x00,0x30,0xA4,0x4C,0x78,0x00, 0x00,0x00,0x00,0x00,0x8C,0x05,0xEC,0x44,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x11,0xF3,0x00,0x2C,0xDD,0xC3,0x3E,0x91,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00, 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x5C,0xFF,0x00,0x01

**Comment by freepdk** [comment]
added with commit: 5a5f46886a5a8df8aceb689dcb433f01ada72525
