### ISSUE TITLE
5XL

### ISSUE THREAD

**Issue by dtomcat** [free-dmo/free-dmo-stm32#2]
Not really an issue (that I know of). But this should work with 5XL right?  Thanks

**Comment by freepdk** [comment]
The logic will work 100% for sure. 
Just the wiring might be different. In case you have some pictures of the main pcb and the RFID board of the 5XL this could be answered easily.

**Comment by dtomcat** [comment]
![5xl_main](https://user-images.githubusercontent.com/1297922/161452054-c2dd2145-96e7-4b22-b996-b2c7c4ad98ec.png)
![5xl_Rfid_back](https://user-images.githubusercontent.com/1297922/161452055-3692bf4e-1837-4e20-ac22-525f67c79393.png)
![5xl_Rfid_front](https://user-images.githubusercontent.com/1297922/161452058-208b4765-6a57-48b7-905e-8e7decd0f4d9.png)

As Requested.

**Comment by freepdk** [comment]
The RFID board is identical to the one in the 550. This means the exact same mod will work for the 5XL as well.

To your question regarding the STM32 "compatible" ICs... Hard to tell if it works or not. The firmware uses I2C which might or might not be cloned in a good way... You have to try.

**Comment by dtomcat** [comment]
This works with 5XL (confirmed)
