### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by TheIgnorantDev** [free-dmo/free-dmo-stm32#28]
I've followed all steps for soldering and programming. Insured the board is correct blue pill even reused the connector from the RFID board to mobo and soldered that to the blue pill board. 

In testing the blue pill powers up. The blue light flashes at boot of the printer. But afterword the 2 of the 3 front lights start flashing on the printer. The same sign that there isn't any labels detected. The connect software says there is a printer on but no labels in the printer.

Is there any way to debug and try to get this issue resolved or get any advice to something I've possibly missed?

Edit: I've both compiled the src and tried precompiled binaries from the release section. I'm not running with the rfid reader attached. Only the blue pill connected to the motherboard of the printer.

**Comment by wr420** [comment]
I believe I am having a similar issue.  I have 4 printers and 4 bluepills.  I successfully installed a precompiled bin file via an FTDI programmer for all 4 pills.  
I tested the first printer and it worked as expected and continues to.  The other 3 are giving me problems and I can figure it out.  Also running without the RFID reader.  
They all show error in windows and I have tried reflashing several times and with different bin files for various label sizes.   I have used cube32 and ST Flash demo to flash with.
