### ISSUE TITLE
Describe RFID board

### ISSUE THREAD

**Issue by stappersg** [free-dmo/free-dmo-stm32#3]
Currently there is no information the RFID board.
It is only seen in a photo.

Please describe the RFID board.

**Comment by freepdk** [comment]
The RFID board is very boring. It is just a CLRC663 RFID IC (used in I2C mode) and an RFID antenna.

The NXP datasheet of CLRC663 has all the details: https://www.nxp.com/docs/en/data-sheet/CLRC663.pdf

**Comment by dtomcat** [comment]
If your question/issue is resolved, please close the issue so attention can be focused on open issues.

**Comment by stappersg** [comment]
@dtomcat  You are right,  thanks for reminding me to do this.

Since a few moments there is merge request #11
