### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by mistial-dev** [free-dmo/free-dmo-stm32#8]
Hello,

Is this largely feature complete?  Are you looking to add more features?

**Comment by freepdk** [comment]
For me it is feature complete. 
I can use the new printer with the normal 3rd party labels (around 15-20 rolls per week, all of the same size). 

Maybe in future some people come up with new ideas.

The project itself also shows the cerators of the "magic SLIX tag" (where you can set UID and data as you wish), that the creation of "magic SLIX2 tags" is useful for 3rd party label manufacturers...

**Comment by mistial-dev** [comment]
Thank you.
